export const GET_DOGS = 'GET_DOGS'
export const GET_ID_DOGS = 'GET_ID_DOGS'
export const GET_TEMPERAMENT = 'GET_TEMPERAMENT'
export const GET_NAME_DOGS = 'GET_NAME_DOGS'
export const SEND_DOGS = 'SEND_DOGS'